[2025-09-07T05:11:18.748+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:11:18.762+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:11:18.763+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:11:18.786+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:11:18.797+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2025-09-07T05:11:18.804+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpig_uzwfv']
[2025-09-07T05:11:18.809+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask extract_sql
[2025-09-07T05:11:18.908+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [running]> on host eb2538915ebb
[2025-09-07T05:11:19.029+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:11:19.033+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:11:19.260+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.608+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.684+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:11:19.749+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-06/sql/agencias.csv', 'data/2025-09-06/sql/clientes.csv', 'data/2025-09-06/sql/colaborador_agencia.csv', 'data/2025-09-06/sql/colaboradores.csv', 'data/2025-09-06/sql/contas.csv', 'data/2025-09-06/sql/propostas_credito.csv']
[2025-09-07T05:11:19.782+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250906T043500, start_date=20250907T051118, end_date=20250907T051119
[2025-09-07T05:11:19.822+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:11:19.851+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:16:28.012+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:16:28.025+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:16:28.025+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:16:28.041+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:16:28.047+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2025-09-07T05:16:28.052+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbmth5ktb']
[2025-09-07T05:16:28.054+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract_sql
[2025-09-07T05:16:28.130+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [running]> on host 31f05607063d
[2025-09-07T05:16:28.532+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:16:28.535+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:16:28.715+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:16:28.857+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:16:28.962+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:16:29.037+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-06/sql/agencias.csv', 'data/2025-09-06/sql/clientes.csv', 'data/2025-09-06/sql/colaborador_agencia.csv', 'data/2025-09-06/sql/colaboradores.csv', 'data/2025-09-06/sql/contas.csv', 'data/2025-09-06/sql/propostas_credito.csv']
[2025-09-07T05:16:29.067+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250906T043500, start_date=20250907T051628, end_date=20250907T051629
[2025-09-07T05:16:29.109+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:16:29.132+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:24:59.298+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:24:59.309+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:24:59.310+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:24:59.327+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:24:59.335+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2025-09-07T05:24:59.343+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfn7n6d4p']
[2025-09-07T05:24:59.348+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask extract_sql
[2025-09-07T05:24:59.431+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [running]> on host 0f971f9b02fb
[2025-09-07T05:24:59.799+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:24:59.802+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:25:00.002+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.148+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.221+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:25:00.268+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-06/sql/agencias.csv', 'data/2025-09-06/sql/clientes.csv', 'data/2025-09-06/sql/colaborador_agencia.csv', 'data/2025-09-06/sql/colaboradores.csv', 'data/2025-09-06/sql/contas.csv', 'data/2025-09-06/sql/propostas_credito.csv']
[2025-09-07T05:25:00.291+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250906T043500, start_date=20250907T052459, end_date=20250907T052500
[2025-09-07T05:25:00.319+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:25:00.338+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T05:31:29.818+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:31:29.831+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T05:31:29.832+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T05:31:29.852+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-06 04:35:00+00:00
[2025-09-07T05:31:29.859+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2025-09-07T05:31:29.866+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptqu9p_zn']
[2025-09-07T05:31:29.873+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask extract_sql
[2025-09-07T05:31:29.943+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [running]> on host 42774f68c6e3
[2025-09-07T05:31:30.279+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T05:31:30.281+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T05:31:30.464+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:31:30.561+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:31:30.651+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-09-07T05:31:30.727+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-06/sql/agencias.csv', 'data/2025-09-06/sql/clientes.csv', 'data/2025-09-06/sql/colaborador_agencia.csv', 'data/2025-09-06/sql/colaboradores.csv', 'data/2025-09-06/sql/contas.csv', 'data/2025-09-06/sql/propostas_credito.csv']
[2025-09-07T05:31:30.752+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250906T043500, start_date=20250907T053129, end_date=20250907T053130
[2025-09-07T05:31:30.802+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T05:31:30.822+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-07T13:39:48.800+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T13:39:48.811+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [queued]>
[2025-09-07T13:39:48.812+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-09-07T13:39:48.830+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_sql> on 2025-09-06 04:35:00+00:00
[2025-09-07T13:39:48.836+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2025-09-07T13:39:48.843+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_sql', 'scheduled__2025-09-06T04:35:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpvrjrvml3']
[2025-09-07T13:39:48.847+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract_sql
[2025-09-07T13:39:48.920+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract_sql scheduled__2025-09-06T04:35:00+00:00 [running]> on host a051b0e1a226
[2025-09-07T13:39:49.248+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-06T04:35:00+00:00'
[2025-09-07T13:39:49.250+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-07T13:39:49.444+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgress = pd.read_sql_query(query, conexao_banco)

[2025-09-07T13:39:49.686+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgress = pd.read_sql_query(query, conexao_banco)

[2025-09-07T13:39:49.838+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_pipeline.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgress = pd.read_sql_query(query, conexao_banco)

[2025-09-07T13:39:49.936+0000] {python.py:202} INFO - Done. Returned value was: ['data/2025-09-06/sql/agencias.csv', 'data/2025-09-06/sql/clientes.csv', 'data/2025-09-06/sql/colaborador_agencia.csv', 'data/2025-09-06/sql/colaboradores.csv', 'data/2025-09-06/sql/contas.csv', 'data/2025-09-06/sql/propostas_credito.csv']
[2025-09-07T13:39:49.963+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract_sql, execution_date=20250906T043500, start_date=20250907T133948, end_date=20250907T133949
[2025-09-07T13:39:50.022+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-07T13:39:50.053+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
